# available modes: development, production
mode: development

server:
  port: 8888

database:
  user: l2sh
  name: admissions
  host: database
  port: 5432
  connection:
    timezone: Europe/Moscow

logging:
  level: debug
