server:
  host: localhost
  port: 8888
  protocol: http

database:
  user: l2sh
  name: admissions
  host: database
  port: 5432
  connection:
    timezone: Europe/Moscow

cache:
  host: cache
  port: 6379

logging:
  # available modes: text, json
  mode: text
  level: debug

auth:
  access_lifetime: 15m
  refresh_lifetime: 720h
  auto_logout: 24h
  passwords:
    min_length: 8
    gen_length: 12
  email_verification:
    token_lifetime: 30m

mailing:
  enabled: true
  api_base: https://api.notisend.ru/v1
