services:
  app:
    container_name: admissions
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

  database:
    image: postgres:latest
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: l2sh
      POSTGRES_USER: l2shdev
      POSTGRES_DB: admissions
    volumes:
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
