services:
  app:
    container_name: admissions
    restart: always
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    command: ./server
    develop:
      watch:
        - action: sync
          path: ./ui/dist
          target: /ui/dist
        - action: rebuild
          path: ./server.go
          target: /server.go
        - action: rebuild
          path: ./handlers
          target: /handlers

  database:
    container_name: database
    image: postgres:latest
    profiles: [ dev ]
    restart: always
    environment:
      POSTGRES_PASSWORD: l2sh
      POSTGRES_USER: l2shdev
      POSTGRES_DB: admissions
    volumes:
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    profiles: [ dev ]
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: l2sh@mail.ru
      PGADMIN_DEFAULT_PASSWORD: l2sh
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "sh", "-c", "until nc -z -v -w30 $(cat /run/secrets/database_host) 5432; do echo waiting for database; sleep 1; done; migrate -path=/migrations -database=$(cat /run/secrets/database_uri) up" ]
    secrets:
      - database_uri
      - database_host

secrets:
  database_uri:
    file: ./secrets/database_uri.txt
  database_host:
    file: ./secrets/database_host.txt

volumes:
  pgadmin:
